[package]
name = "image-resizer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-multipart = "0.4"
image = "0.24"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
env_logger = "0.9"