[package]
name = "image-resizer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
actix-multipart = "0.6.1"
image = "0.24.7"
tokio = { version = "1.35.0", features = ["full"] }
futures = "0.3.29"
env_logger = "0.10.1"
actix-cors = "0.6"
log = "0.4"